- hosts: server
  vars:
  - image: nagalapar/cicd-jenkins:beta
  - python: python-docker
  tasks:
  - name: install python docker centos
    yum:
      name: "{{ python }}"
      state: present
    when:
    - ansible_distribution == "CentOS"
  - name: install python docker ubuntu
    apt:
      name: python3-pip
      state: present
    when:
    - ansible_distribution == "Ubuntu"
  - name: uninstall python docker
    apt:
      name: python-docker
      state: absent
    when:
    - ansible_distribution == "Ubuntu"
  - name: install python docker-py
    pip:
      name: docker-py
      state: present
    when:
    - ansible_distribution == "Ubuntu"
  - name: pull image dari docker hub
    docker_image:
      name: "{{ image }}"
      state: present
      force: yes
  - name: create container
    docker_container:
      name: docker_container_jenkins
      image: "{{ image }}"
      state: present
      published_ports:
      - 8090:80
      recreate: yes
